name: 'Check Atlantis config'
description: 'Run set of checks on atlantis.yaml config file.'
inputs:
  atlantis-config-path:
    description: 'Full path to Atlantis config file. Default is atlantis.yaml in the root directory'
    default: 'atlantis.yaml'
    required: true
  commit-change:
    description: 'Commit the necessary updates back to PR'
    default: 'false'
    required: false
  sort-by:
    description: 'Sort atlantis projects by the given key ("name" or "dir")'
    default: 'dir'
    required: false
  token:
    description: 'GitHub auth token. For most cases set it to secrets.GITHUB_TOKEN'
    default: ${{ github.token }}
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
